package com.laberit.sina.bootcamp.extra.awesomefinalproject.model.enums;

public enum Disease {
    FEVER, DIABETES, HEART_DISEASE, CANCER, COVID_19, FLU, COLD, ASTHMA, HYPERTENSION, OBESITY, DEPRESSION, PNEUMONIA,
    HIV, TUBERCULOSIS, MALARIA, CHOLERA, TYPHOID, MENINGITIS, EPILEPSY, SCHIZOPHRENIA, BIPOLAR_DISORDER, ALZHEIMER,
    PARKINSON, STROKE, MULTIPLE_SCLEROSIS, RHEUMATOID_ARTHRITIS, LUPUS, CROHNS_DISEASE, ULCERATIVE_COLITIS,
    CELIAC_DISEASE, CHRONIC_KIDNEY_DISEASE, CHRONIC_LIVER_DISEASE, CHRONIC_LUNG_DISEASE, CHRONIC_HEART_DISEASE,
    CHRONIC_PANCREATITIS, CHRONIC_DIARRHEA, CHRONIC_CONSTIPATION, CHRONIC_GASTRITIS, CHRONIC_GASTROENTERITIS,
    CHRONIC_GASTRIC_ULCER, CHRONIC_GASTRIC_CANCER, CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE, CHRONIC_BRONCHITIS,
    CHRONIC_ASTHMA, CHRONIC_EMPHYSEMA, CHRONIC_LUNG_CANCER, CHRONIC_HEART_ATTACK, CHRONIC_HEART_FAILURE,
    CHRONIC_HEART_ARREST, CHRONIC_HEART_CANCER, CHRONIC_PANCREATIC_CANCER, CHRONIC_LIVER_CANCER,
    CHRONIC_COLORECTAL_CANCER, CHRONIC_STOMACH_CANCER, CHRONIC_OESOPHAGEAL_CANCER, CHRONIC_BRAIN_CANCER,
    CHRONIC_BREAST_CANCER, CHRONIC_OVARIAN_CANCER, CHRONIC_CERVICAL_CANCER, CHRONIC_PROSTATE_CANCER,
    CHRONIC_TESTICULAR_CANCER, CHRONIC_PENILE_CANCER, CHRONIC_LARYNGEAL_CANCER, CHRONIC_THYROID_CANCER,
    CHRONIC_PARATHYROID_CANCER, CHRONIC_ADRENAL_CANCER, CHRONIC_PITUITARY_CANCER, CHRONIC_PINEAL_CANCER,
    CHRONIC_THYMIC_CANCER
}
