package com.laberit.sina.bootcamp.extra.awesomefinalproject.model.enums;

public enum Permissions {
    REGISTER_USER, MODIFY_USER, DELETE_USER, WATCH_USERS,
    WATCH_PATIENT_INFO, CREATE_DIAGNOSIS, MODIFY_DIAGNOSIS, DELETE_DIAGNOSIS, WATCH_DIAGNOSIS,
    CREATE_APPOINTMENT, MODIFY_APPOINTMENT, DELETE_APPOINTMENT, WATCH_PATIENT_APPOINTMENTS,
    WATCH_PATIENT_STATISTICS, WATCH_APPOINTMENT_STATISTICS
}
