package com.laberit.sina.bootcamp.extra.awesomefinalproject.model.enums;

public enum Permissions {
    REGISTER_USER, UPDATE_USER, DELETE_USER, WATCH_USERS,
    WATCH_PATIENT_INFO, CREATE_DIAGNOSIS, UPDATE_DIAGNOSIS, DELETE_DIAGNOSIS, WATCH_DIAGNOSIS,
    CREATE_APPOINTMENT, CONFIRM_APPOINTMENT, UPDATE_APPOINTMENT, DELETE_APPOINTMENT, WATCH_PATIENT_APPOINTMENTS,
    WATCH_PATIENT_STATISTICS, WATCH_APPOINTMENT_STATISTICS
}
